// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkXPqpE9QmYVDA-XwQibVRRGydeusEOLw',
    appId: '1:937547906227:web:63ad5a0ac28a5c87bb04c6',
    messagingSenderId: '937547906227',
    projectId: 'ai-quiz-tutor',
    authDomain: 'ai-quiz-tutor.firebaseapp.com',
    storageBucket: 'ai-quiz-tutor.firebasestorage.app',
    measurementId: 'G-W4CQWZYR73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm_wVPxISG3NcpQGMAMf2A47Vg2aIQ_JY',
    appId: '1:937547906227:android:9d117b819c7d61d3bb04c6',
    messagingSenderId: '937547906227',
    projectId: 'ai-quiz-tutor',
    storageBucket: 'ai-quiz-tutor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzqiitnzAtRN4-lF5S2rl8zlF9kfaJN5c',
    appId: '1:937547906227:ios:ce25647cebb4cf46bb04c6',
    messagingSenderId: '937547906227',
    projectId: 'ai-quiz-tutor',
    storageBucket: 'ai-quiz-tutor.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzqiitnzAtRN4-lF5S2rl8zlF9kfaJN5c',
    appId: '1:937547906227:ios:ce25647cebb4cf46bb04c6',
    messagingSenderId: '937547906227',
    projectId: 'ai-quiz-tutor',
    storageBucket: 'ai-quiz-tutor.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkXPqpE9QmYVDA-XwQibVRRGydeusEOLw',
    appId: '1:937547906227:web:03974ad2c674476cbb04c6',
    messagingSenderId: '937547906227',
    projectId: 'ai-quiz-tutor',
    authDomain: 'ai-quiz-tutor.firebaseapp.com',
    storageBucket: 'ai-quiz-tutor.firebasestorage.app',
    measurementId: 'G-K1JV7T349W',
  );
}
